# Based on: https://gist.github.com/yonglai/d4617d6914d5f4eb22e4e5a15c0e9a03
---

# Required for docker: sudo yum install -y yum-utils device-mapper-persistent-data lvm2
- name: Install docker requirements for repository
  yum:
    name: 
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    state: latest

- name: Enable CENTOS repos(CentOS only)
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: "{{ item }}"
    option: enabled
    value: 1
  with_items:
    - base
    - updates
    - extras    # Required for docker-ce
    - centosplus
  when:
    - (ansible_distribution == "CentOS")
    -   ansible_distribution_major_version == "7"

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: yes
  
- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: yes

- name: install docker and start the daemon
  yum: name=docker-ce state=latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: create docker group
  group: name=docker state=present

- name: add users to the docker group
  user:
    name: "{{docker_centos_users}}"
    groups: docker
    append: yes