---
# tasks file for centos_install

- name: update all packages
  yum:
    name: "*"
    state: latest
    ### If you need to avoid update some packages
    # exclude: xxx*
  become: Yes
  when: yum_update == "Yes"

- name: install yum utils
  yum:
    name:
    - yum-utils
    - "@Development tools"
    state: latest
  become: Yes

- name: install epel-release
  yum:
    name: epel-release
    state: latest
  become: Yes

- name: add repository for python36u
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: installed
  become: Yes

- name: install python3 python-pip
  yum:
    name: 
    # - ius-release.rpm
    - python36u
    - python36u-libs
    - python36u-devel
    - python36u-pip
    - python-pip
    - python-devel
    # - python34
    state: latest
  become: Yes

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
  become: Yes

- name: install base apps
  yum:
    name: "{{ yum_apps }}"
    ### Remove any packages not required
    # - vim
    # - git
    # - ansible
    state: latest
  become: Yes

# tasks for ansible-disable-selinux
- name: Install libselinux as prerequisite for SELinux Ansible module
  yum:
    name: 
    - libselinux-python
    - libsemanage-python
    state: latest
  become: Yes

# Disable SELINUX (requires reboot)
- name: Disable SELinux at next reboot
  selinux:
    state: disabled
  become: Yes

# Install and enable docker
- include: docker_install_centos.yml

# VS Code Related tasks
- include: vs_code_install_centos.yml